services:
  mongodb:
    image: mongo:latest
    container_name: rpg-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: rpg-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  rpg-backend:
    build:
      context: ./rpg-backend
      dockerfile: Dockerfile
    container_name: rpg-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/rpg-life
      - JWT_SECRET=rpg_life_super_secret_jwt_key_2026
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
    restart: always

  rpg-frontend:
    build:
      context: ./rpg-frontend
      dockerfile: Dockerfile
    container_name: rpg-frontend
    ports:
      - "3000:80"
    depends_on:
      - rpg-backend
    restart: always

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:
