/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EconomyController_getCoins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfileController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfileController_updateProfile"];
        trace?: never;
    };
    "/profile/nutrition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfileController_updateNutrition"];
        trace?: never;
    };
    "/activity/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ActivityController_logSteps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/steps/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActivityController_getTodaySteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/steps/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActivityController_getStepsRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NutritionController_createLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/getDailySummary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NutritionController_getDailySumaty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/log/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["NutritionController_deleteLog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NutritionController_getAllFoods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/barcode/{barcode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NutritionController_getByBarcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutController_getUserWorkouts"];
        put?: never;
        post: operations["WorkoutController_createWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutController_getWorkoutById"];
        put: operations["WorkoutController_updateWorkout"];
        post?: never;
        delete: operations["WorkoutController_deleteWorkout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutController_getAllWorkouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkoutController_createWorkoutLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/logs/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutController_getUserWorkoutLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkoutController_logWorkoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/progression/{exerciseName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkoutController_getProgression"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/energy/daily-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtém o resumo calórico diário (TMB, GET, Treinos, Passos, Refeições e Saldo) */
        get: operations["EnergyController_getDailySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/energy/weekly-budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtém o orçamento calórico semanal e o buffer acumulado para o fim de semana (Cofre) */
        get: operations["EnergyController_getWeeklyBudget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterUserDto: {
            /** Format: email */
            email: string;
            username: string;
            password: string;
            /** @enum {string} */
            role: "player" | "admin";
        };
        RegisterResponseDto: {
            id: string;
            /** Format: email */
            email: string;
            username: string;
            /** @enum {string} */
            role: "player" | "admin";
        };
        ErrorResponseDto: {
            /** @example 400 */
            statusCode: number;
            message: string | string[];
            /** @example Bad Request */
            error: string;
        };
        LoginUserDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            access_Token: string;
        };
        GetMeResponseDto: {
            user: {
                _id: string;
                /** Format: email */
                email: string;
                username: string;
                /** @enum {string} */
                role: "player" | "admin";
            };
            profile?: {
                _id?: string;
                weightKg?: number | null;
                heightCm?: number | null;
                age?: number | null;
                biologicalSex?: string | null;
                activityLevel?: string | null;
                primaryGoal?: string | null;
                targetCalories?: number | null;
                targetProteinGrams?: number | null;
                targetCarbGrams?: number | null;
                targetFatGrams?: number | null;
                timezone?: string;
            } | null;
            progress?: {
                level: number;
                currentXp: number;
                nextLevelXp: number;
                currentStreak: number;
                bestStreak: number;
            } | null;
            coinBalance: number;
        };
        LogoutResponseDto: {
            message: string;
        };
        CoinsResponseDto: {
            balance: number;
            entries: {
                id: string;
                amount: number;
                /** @enum {string} */
                reason: "day_close" | "workout" | "steps_goal" | "streak_7" | "ticket";
                refId?: string;
                createdAt: string;
            }[];
        };
        UpdateProfileDto: {
            weightKg?: number;
            heightCm?: number;
            age?: number;
            /** @enum {string} */
            biologicalSex?: "male" | "female" | "other";
            /** @enum {string} */
            activityLevel?: "sedentary" | "light" | "moderate" | "intense" | "very_intense";
            /** @enum {string} */
            primaryGoal?: "lose_weight" | "maintain" | "gain_muscle";
            timezone?: string;
        };
        LogStepsDto: {
            steps: number;
            date?: string;
            /**
             * @default manual
             * @enum {string}
             */
            source?: "manual" | "health_connect" | "healthkit";
        };
        LogStepsResponseDto: {
            date: string;
            steps: number;
            caloriesBurned: number;
            coinsEarned: number;
            coinsAwardedToday: number;
            recommendedSteps: number;
            reasoning: string;
        };
        GetStepsResponseDto: {
            date: string;
            steps: number;
            caloriesBurned: number;
            coinsEarned: number;
            recommendedSteps: number;
            reasoning: string;
        };
        StepsRecommendationResponseDto: {
            recommendedSteps: number;
            reasoning: string;
        };
        CreateFoodLogDto: {
            foodName: string;
            /** @enum {string} */
            mealType: "breakfast" | "lunch" | "dinner" | "snack";
            amountGrams: number;
            calories: number;
            proteinGrams: number;
            carbGrams: number;
            fatGrams: number;
            date?: string;
        };
        CreateWorkoutDtoClass: {
            title: string;
            /** @default  */
            description: string;
            /** @default 45 */
            estimatedMinutes: number;
            /** @default [] */
            targetMuscleGroups: string[];
            /** @default [] */
            scheduledDays: number[];
            /**
             * @default moderate
             * @enum {string}
             */
            intensity: "moderate" | "intense" | "cycling_running";
            /** @default [] */
            exercises: {
                id?: string;
                name: string;
                /**
                 * @default Peito
                 * @enum {string}
                 */
                category: "Peito" | "Costas" | "Pernas" | "Ombros" | "Braços" | "Abdômen" | "Cardio";
                /**
                 * @default strength
                 * @enum {string}
                 */
                primaryAttribute: "strength" | "intelligence" | "vitality" | "focus";
                /** @default [] */
                sets: {
                    id?: string;
                    /** @default 1 */
                    setNumber: number;
                    /** @default 0 */
                    weightKg: number;
                    /** @default 0 */
                    reps: number;
                    /** @default false */
                    completed: boolean;
                    rpe?: number;
                    /**
                     * @default normal
                     * @enum {string}
                     */
                    technique: "normal" | "back_off_set" | "cluster_set" | "drop_set";
                    /** @default 60 */
                    restSeconds: number;
                }[];
                notes?: string;
            }[];
            /** @default 0 */
            completionCount: number;
            lastCompletedDate?: string | null;
        };
        UpdateWorkoutDtoClass: {
            title?: string;
            /** @default  */
            description: string;
            /** @default 45 */
            estimatedMinutes: number;
            /** @default [] */
            targetMuscleGroups: string[];
            /** @default [] */
            scheduledDays: number[];
            /**
             * @default moderate
             * @enum {string}
             */
            intensity: "moderate" | "intense" | "cycling_running";
            /** @default [] */
            exercises: {
                id?: string;
                name: string;
                /**
                 * @default Peito
                 * @enum {string}
                 */
                category: "Peito" | "Costas" | "Pernas" | "Ombros" | "Braços" | "Abdômen" | "Cardio";
                /**
                 * @default strength
                 * @enum {string}
                 */
                primaryAttribute: "strength" | "intelligence" | "vitality" | "focus";
                /** @default [] */
                sets: {
                    id?: string;
                    /** @default 1 */
                    setNumber: number;
                    /** @default 0 */
                    weightKg: number;
                    /** @default 0 */
                    reps: number;
                    /** @default false */
                    completed: boolean;
                    rpe?: number;
                    /**
                     * @default normal
                     * @enum {string}
                     */
                    technique: "normal" | "back_off_set" | "cluster_set" | "drop_set";
                    /** @default 60 */
                    restSeconds: number;
                }[];
                notes?: string;
            }[];
            /** @default 0 */
            completionCount: number;
            lastCompletedDate?: string | null;
        };
        EnergyDailySummaryResponseDto: {
            date: string;
            summary: {
                bmr: number;
                tdee: number;
                activityCaloriesBurned: number;
                totalBurnedCalories: number;
                totalCaloriesConsumed: number;
                remainingCalorieBudget: number;
                netCalorieBalance: number;
                totalCoinsEarned: number;
            };
            breakdown: {
                workouts: {
                    totalCalories: number;
                    coinsEarned: number;
                    count: number;
                    items?: {
                        routineName?: string;
                        durationMinutes?: number;
                        intensity?: string;
                        caloriesBurned?: number;
                        coinsGained?: number;
                    }[];
                };
                steps: {
                    count: number;
                    caloriesBurned: number;
                    coinsEarned: number;
                };
            };
        };
        WeeklyBudgetResponseDto: {
            weekRange: {
                start: string;
                end: string;
            };
            tdee: number;
            accumulatedWeekDeficit: number;
            weekendBufferTotal: number;
            weekendBufferPerDay: number;
            dailyRecords?: {
                date: string;
                dayOfWeek: number;
                isWeekday: boolean;
                tdee: number;
                caloriesBurned: number;
                totalBudget: number;
                consumed: number;
                savedCalories: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
            /** @description Dados de entrada inválidos / Erro de Validação */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autorizado / Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Conflito (Ex: Registro duplicado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Erro interno do servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Dados de entrada inválidos / Erro de Validação */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autorizado / Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Conflito (Ex: Registro duplicado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Erro interno do servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna o perfil completo do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMeResponseDto"];
                };
            };
            /** @description Dados de entrada inválidos / Erro de Validação */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autorizado / Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Conflito (Ex: Registro duplicado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Erro interno do servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Realiza logout limpando o cookie HttpOnly */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
            /** @description Dados de entrada inválidos / Erro de Validação */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autorizado / Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Conflito (Ex: Registro duplicado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Erro interno do servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    EconomyController_getCoins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saldo de moedas e extrato recente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoinsResponseDto"];
                };
            };
        };
    };
    ProfileController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_updateNutrition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ActivityController_logSteps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogStepsDto"];
            };
        };
        responses: {
            /** @description Passos registrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogStepsResponseDto"];
                };
            };
        };
    };
    ActivityController_getTodaySteps: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passos do dia (ou da data informada) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStepsResponseDto"];
                };
            };
        };
    };
    ActivityController_getStepsRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meta diaria de passos recomendada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepsRecommendationResponseDto"];
                };
            };
        };
    };
    NutritionController_createLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFoodLogDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NutritionController_getDailySumaty: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NutritionController_deleteLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NutritionController_getAllFoods: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NutritionController_getByBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                barcode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_getUserWorkouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_createWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkoutDtoClass"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_getWorkoutById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_updateWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkoutDtoClass"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_deleteWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_getAllWorkouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_createWorkoutLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_getUserWorkoutLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_logWorkoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutController_getProgression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EnergyController_getDailySummary: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumo calórico e detalhamento por atividade retornado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnergyDailySummaryResponseDto"];
                };
            };
        };
    };
    EnergyController_getWeeklyBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orçamento semanal retornado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyBudgetResponseDto"];
                };
            };
        };
    };
}
